management:
  trace:
    enabled: true
    include: AUTHORIZATION_HEADER, COOKIE_HEADERS, PRINCIPAL, REMOTE_ADDRESS, REQUEST_HEADERS, RESPONSE_HEADERS, SESSION_ID, TIME_TAKEN
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.web.filter.CommonsRequestLogging: DEBUG
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: TRACE
    reactor.netty.http.client: TRACE
server:
  port : 8443
  forward-headers-strategy: framework
  servlet:
    context-path: /ms-user-service
#hostname: ms-user-service:8081
spring:
  application:
    name: ms-user-service
  flyway:
    enabled: true
    baseline-on-migrate : true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      This config will override the flyway because it will drop the user schema flyway
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://twitter-db-tranbaotin270402-c9d4.i.aivencloud.com:27368/defaultdb?sslmode=require
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driverClassName: org.postgresql.Driver
  rabbitmq:
    addresses: amqps://gqupsbui:sNGBVBZF4XIuUNvAnYWfOWJ8mUiUTUAr@armadillo.rmq.cloudamqp.com/gqupsbui
#    host: armadillo.rmq.cloudamqp.com
#    port: 5672
#    username: gqupsbui
#    password: sNGBVBZF4XIuUNvAnYWfOWJ8mUiUTUAr
  data:
    redis:
#      url: rediss://red-coh99qev3ddc73fkf190:ZFBBFUT5GfKDJHH0T5Zo8A1VVny8skwL@singapore-redis.render.com:6379
      host: singapore-redis.render.com
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      port: '6379'
      database: '0'
      timeout: '60000'
      ssl:
        enabled: true

rabbitmq:
  internal-mail:
    exchanges: internal.exchange
    routing-keys: internal.mail.routing-key

jwt:
  secret: 208bc47b3e1ee5554e388c735b9f234f89ac246e8ce463c8313fc1cff16e760e

service:
  downstream-url:
    ms-image-service: https://ms-image-service-kfnp.onrender.com
    ms-notification-service: https://ms-notification-service.onrender.com

eureka:
  instance:
    hostname: ms-user-service-ndm5.onrender.com  # Public domain name
    nonSecurePort: 443  # Standard HTTP port
    securePortEnabled: true  # Enable if you're using HTTPS
    preferIpAddress: false  # Use the hostname instead of the IP address
    statusPageUrlPath: /actuator/info  # Default status page path
    healthCheckUrlPath: /actuator/health  # Default health check path
  client:
    serviceUrl:
      defaultZone: https://ms-eureka-server-2cvn.onrender.com/eureka
    fetch-registry: true
    register-with-eureka: true
  # instance:
  #   hostname: ${EUREKA_HOST:localhost}