/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.twitter.ms.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserSubscriptionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7356957845710091966L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserSubscriptionEvent\",\"namespace\":\"com.twitter.ms.event\",\"fields\":[{\"name\":\"user_id\",\"type\":\"long\"},{\"name\":\"subscriber_id\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserSubscriptionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserSubscriptionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserSubscriptionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserSubscriptionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserSubscriptionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserSubscriptionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserSubscriptionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserSubscriptionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserSubscriptionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  public long user_id;
  public long subscriber_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserSubscriptionEvent() {}

  /**
   * All-args constructor.
   * @param user_id The new value for user_id
   * @param subscriber_id The new value for subscriber_id
   */
  public UserSubscriptionEvent(java.lang.Long user_id, java.lang.Long subscriber_id) {
    this.user_id = user_id;
    this.subscriber_id = subscriber_id;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return subscriber_id;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = (java.lang.Long)value$; break;
    case 1: subscriber_id = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return The value of the 'user_id' field.
   */
  public long getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'subscriber_id' field.
   * @return The value of the 'subscriber_id' field.
   */
  public long getSubscriberId() {
    return subscriber_id;
  }


  /**
   * Sets the value of the 'subscriber_id' field.
   * @param value the value to set.
   */
  public void setSubscriberId(long value) {
    this.subscriber_id = value;
  }

  /**
   * Creates a new UserSubscriptionEvent RecordBuilder.
   * @return A new UserSubscriptionEvent RecordBuilder
   */
  public static com.twitter.ms.event.UserSubscriptionEvent.Builder newBuilder() {
    return new com.twitter.ms.event.UserSubscriptionEvent.Builder();
  }

  /**
   * Creates a new UserSubscriptionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserSubscriptionEvent RecordBuilder
   */
  public static com.twitter.ms.event.UserSubscriptionEvent.Builder newBuilder(com.twitter.ms.event.UserSubscriptionEvent.Builder other) {
    if (other == null) {
      return new com.twitter.ms.event.UserSubscriptionEvent.Builder();
    } else {
      return new com.twitter.ms.event.UserSubscriptionEvent.Builder(other);
    }
  }

  /**
   * Creates a new UserSubscriptionEvent RecordBuilder by copying an existing UserSubscriptionEvent instance.
   * @param other The existing instance to copy.
   * @return A new UserSubscriptionEvent RecordBuilder
   */
  public static com.twitter.ms.event.UserSubscriptionEvent.Builder newBuilder(com.twitter.ms.event.UserSubscriptionEvent other) {
    if (other == null) {
      return new com.twitter.ms.event.UserSubscriptionEvent.Builder();
    } else {
      return new com.twitter.ms.event.UserSubscriptionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserSubscriptionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserSubscriptionEvent>
    implements org.apache.avro.data.RecordBuilder<UserSubscriptionEvent> {

    private long user_id;
    private long subscriber_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.twitter.ms.event.UserSubscriptionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.subscriber_id)) {
        this.subscriber_id = data().deepCopy(fields()[1].schema(), other.subscriber_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UserSubscriptionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.twitter.ms.event.UserSubscriptionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subscriber_id)) {
        this.subscriber_id = data().deepCopy(fields()[1].schema(), other.subscriber_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * @return The value.
      */
    public long getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public com.twitter.ms.event.UserSubscriptionEvent.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * @return This builder.
      */
    public com.twitter.ms.event.UserSubscriptionEvent.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriber_id' field.
      * @return The value.
      */
    public long getSubscriberId() {
      return subscriber_id;
    }


    /**
      * Sets the value of the 'subscriber_id' field.
      * @param value The value of 'subscriber_id'.
      * @return This builder.
      */
    public com.twitter.ms.event.UserSubscriptionEvent.Builder setSubscriberId(long value) {
      validate(fields()[1], value);
      this.subscriber_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriber_id' field has been set.
      * @return True if the 'subscriber_id' field has been set, false otherwise.
      */
    public boolean hasSubscriberId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subscriber_id' field.
      * @return This builder.
      */
    public com.twitter.ms.event.UserSubscriptionEvent.Builder clearSubscriberId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserSubscriptionEvent build() {
      try {
        UserSubscriptionEvent record = new UserSubscriptionEvent();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.Long) defaultValue(fields()[0]);
        record.subscriber_id = fieldSetFlags()[1] ? this.subscriber_id : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserSubscriptionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserSubscriptionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserSubscriptionEvent>
    READER$ = (org.apache.avro.io.DatumReader<UserSubscriptionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.user_id);

    out.writeLong(this.subscriber_id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.user_id = in.readLong();

      this.subscriber_id = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.user_id = in.readLong();
          break;

        case 1:
          this.subscriber_id = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










